### ISSUE TITLE
Migration no. 0006 is not reversible

### ISSUE THREAD

**Issue by sanchit-mathew** [jazzband/django-oauth-toolkit#1194]
**Describe the bug**
The migration file `0006_alter_application_client_secret.py` is not reversible. On attempting to migrate backwards i.e. rollback model changes, `Django` raises an `IrreversibleError`. 
This is due to Python code being run which doesn't specify a `reverse_code`

**To Reproduce**
1. Checkout to any branch >= `2.0.0` including `master`
2. Run all migrations
3. Undo all migrations (`./python manage.py migrate zero`) or just undo the 6th migration (`./python manage.py migrate 0005`)

**Expected behavior**
All `django-oauth-toolkit` migrations should be reversible

**Version**
`2.1.0`

- [x] I have tested with the latest published release and it's still a problem.
- [x] I have tested with the master branch and it's still a problem.

**Additional context**
Stack Trace:
```
Traceback (most recent call last):
  File "/Users/sanchit-matt/.venvs/work/bin/krypton", line 5, in <module>
    main()
  File "/Users/sanchit-matt/work/krypton/src/krypton/runner/__init__.py", line 49, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sanchit-matt/work/krypton/src/krypton/runner/commands/django.py", line 22, in django
    execute_from_command_line(argv=[ctx.command_path] + list(management_args))
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 33, in handle
    executor.run_migrations(tenants=[self.schema_name])
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/tenant_schemas/migration_executors/base.py", line 58, in run_migrations
    run_migrations(self.args, self.options, self.codename, public_schema_name)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/tenant_schemas/migration_executors/base.py", line 31, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/db/migrations/executor.py", line 121, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/db/migrations/executor.py", line 196, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/Users/sanchit-matt/.venvs/work/lib/python3.8/site-packages/django/db/migrations/migration.py", line 149, in unapply
    raise IrreversibleError("Operation %s in %s is not reversible" % (operation, self))
django.db.migrations.exceptions.IrreversibleError: Operation <RunPython <function forwards_func at 0x11445f4c0>> in oauth2_provider.0006_alter_application_client_secret is not reversible
```
**The fix should be as simple as adding `reverse_code=migrations.RunPython.noop` in the `migrations.RunPython` call**

**Comment by n2ygk** [comment]
It's not reversible because you can't undo a one-way hash.

**Comment by sanchit-mathew** [comment]
> It's not reversible because you can't undo a one-way hash.

@n2ygk I agree, that's why I suggested to keep `RunPython.noop` as the reverse code. Since we can't reverse a one-way hash, the next best thing is to ask Django to simply do nothing so that the migration, on paper, gets reversed

**Comment by n2ygk** [comment]
That might mislead people into thinking things aren’t messed up when they
are vs. restoring a db from backup or similar to revert the data.

**Comment by dopry** [comment]
Rollback from 0006 is not supported.
