### ISSUE TITLE
Initial Migrate Error

### ISSUE THREAD

**Issue by leferaycloud** [jazzband/django-oauth-toolkit#527]
I am trying to follow the getting started tutorial for django oauth toolkit from:

https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html

When I run Migrate, I get this error:

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 1003, in _constraint_names if type_ is not None and infodict['type'] != type_: KeyError: 'type'
Any help would be appreciated.

---Complete Stack trace ----

```pytb
Operations to perform: Apply all migrations: admin, auth, contenttypes, oauth2_provider, sessions Running migrations: Applying oauth2_provider.0004_auto_20160525_1623...Traceback (most recent call last): File "/Users/lr/lrapp1/manage.py", line 22, in execute_from_command_line(sys.argv) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/init.py", line 364, in execute_from_command_line utility.execute() File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/init.py", line 356, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv self.execute(*args, **cmd_options) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute output = self.handle(*args, **options) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle fake_initial=fake_initial, File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration state = migration.apply(state, schema_editor) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply operation.database_forwards(self.app_label, schema_editor, old_state, project_state) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards schema_editor.alter_field(from_model, from_field, to_field) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 515, in alter_field old_db_params, new_db_params, strict) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 572, in _alter_field index_names = self._constraint_names(model, [old_field.column], index=True, type_=Index.suffix) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 1003, in _constraint_names if type_ is not None and infodict['type'] != type_: KeyError: 'type'
```

**Comment by aravindprasanna** [comment]
I am facing the same issue as well. Did you receive any updates ?

**Comment by smn-snkl** [comment]
Same here. Any update would be highly appreciated!

**Comment by vdnclodio** [comment]
Same issue with:
- Django 2.1.5
- mysql-cvonnector-python 8.0.13
- django-oauth-toolkit 1.2.0

Here is the co:mplete stack trace : 
```
Tracking file by folder pattern:  migrations
Operations to perform:
  Apply all migrations: oauth2_provider
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying oauth2_provider.0001_initial... OK
  Applying oauth2_provider.0002_08_updates... OK
  Applying oauth2_provider.0003_auto_20160316_1503... OK
  Applying oauth2_provider.0004_auto_20160525_1623...Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pycharm\django_manage.py", line 52, in <module>
    run_command()
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pycharm\django_manage.py", line 46, in run_command
    run_module(manage_file, None, '__main__', True)
  File "C:\Program Files\Python37\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:/Users/Claudio/PycharmProjects/pypress_oauth\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\core\management\commands\migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\db\migrations\operations\fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\db\backends\base\schema.py", line 523, in alter_field
    old_db_params, new_db_params, strict)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\db\backends\base\schema.py", line 585, in _alter_field
    index_names = self._constraint_names(model, [old_field.column], index=True, type_=Index.suffix)
  File "C:\Users\Claudio\PycharmProjects\pypress_oauth\venv\lib\site-packages\django\db\backends\base\schema.py", line 1043, in _constraint_names
    if type_ is not None and infodict['type'] != type_:
KeyError: 'type'

Process finished with exit code 1```

**Comment by marcosajc** [comment]
All of you are using Djongo ? I am getting the exact same error so decided to try connecting with postgres and it went fine. For me it feels like an issue with Djongo instead, but not sure...

**Comment by vdnclodio** [comment]
As far as i can tell, this bug only happen with mysql database. In my case i was using the mysql-python-connector 8.0.13.
Switching to sqlite backend or postgressql backend fixed the issue for me.

**Comment by MMohamad70** [comment]
Same problem when using djongo. Is there any solution or workaround?

**Comment by amitsarwara** [comment]
> Same problem when using django. Is there any solution or workaround?

If you got the solution, please add that in comment i have seen many users are looking for the solution.

**Comment by LiteWait** [comment]
Please tell me someone is working on this or has a workaround.

**Comment by amitsarwara** [comment]
@LiteWait, I got this error while working with Djongo (A third party mongo connector) as stated by @MMohamad70, @marcosajc. 

**NOTE: It might be the stupidest way to do the thing but I was able to continue the development. This is a change that I made in Django core module which anyone can guess is the worst way to do but I reverted my changes after successful migration. For that project i didn't get any issue till date.**

Following was the change
`lib/python3.7/site-packages/django/db/backends/base/schema.py
Line No: 602
Replace-: model, [old_field.column], index=True,
With-: model, [old_field.column], index=True, type_=Index.suffix,
`

because in case of fourth migration type_ value is none so it raises an exception.

**Comment by kcathey** [comment]
I had this issue with djongo, and found that putting in a relational database for oauth2_provider solved the problem.
