### ISSUE TITLE
Authentication failed: unauthorized_client

### ISSUE THREAD

**Issue by rafahsolis** [jazzband/django-oauth-toolkit#682]
Hello, I'm having trouble implementing an Oauth2 server with django-oauth-toolkit and connecting client with social_auth.
My client does corectly redirect to the oauth server login page, but when the server returns the redirect i get an error message:

    AuthFailed at /complete/mybackend/ 
    Authentication failed: unauthorized_client

I've been trying to debug this but it's a bit hard, what i found out is that the oauth server is the one returning this message, but if i try to login directly with the same user to the oauth server it works.
I'm using:
## Server
Python 3.6.7
Django==2.1.4
django-oauth-toolkit==1.2.0

## Client
Python 3.6.7
Django==2.1.4
social-auth-app-django==3.1.0

### Here is the full traceback that i get on the client server:
    Internal Server Error: /complete/mybackend/
    Traceback (most recent call last):
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
        response = get_response(request)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
        response = self.process_exception_by_middleware(e, request)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
        response = view_func(request, *args, **kwargs)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
        return view_func(*args, **kwargs)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/social_django/utils.py", line 49, in wrapper
        return func(request, backend, *args, **kwargs)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/social_django/views.py", line 34, in complete
        *args, **kwargs)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/social_core/actions.py", line 43, in do_complete
        user = backend.complete(user=user, *args, **kwargs)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/social_core/backends/base.py", line 40, in complete
        return self.auth_complete(*args, **kwargs)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/social_core/utils.py", line 259, in wrapper
        return func(*args, **kwargs)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/social_core/backends/oauth.py", line 391, in auth_complete
        self.process_error(self.data)
    File "/home/ubuntu/.virtualenvs/Oauth2Client/lib/python3.6/site-packages/social_core/backends/oauth.py", line 383, in process_error
        data['error'])
    social_core.exceptions.AuthFailed: Authentication failed: unauthorized_client
    [20/Dec/2018 10:34:39] "GET /complete/mybackend/?redirect_state=EQWtzLd****************I9DNIhJD6&error=unauthorized_client&state=EQWtzLd2RG****************NIhJD6 HTTP/1.1" 500 106974

I coudn't find out why this is happening yet...

**Comment by rafahsolis** [comment]
After a lot of debugging, i think i found my problem.
The error was being generated by oauth2_validators.OAuth2Validator.validate_response_type() that has the following code:

        if response_type == "code":
            return client.allows_grant_type(AbstractApplication.GRANT_AUTHORIZATION_CODE)
        elif response_type == "token":
            return client.allows_grant_type(AbstractApplication.GRANT_IMPLICIT)
        else:
            return False

But i didn't find "code" in AbstractApplication. There is a "authorization-code" but no "code", so client.allows_grant_type(AbstractApplication.GRANT_AUTHORIZATION_CODE) would return True using "authorization-code" and False with "code", but because we have a == condition this can never work.
¿Is this a bug?

**Comment by rafahsolis** [comment]
Hi, sorry for the late response, i lost track of the issue, the value of response_type is: authorization-code


    DEBUG 2019-03-13 10:34:09,016 authorization_code 14875 139629690451712 Using provided redirect_uri http://oauthclient:8001/complete/rra/?redirect_state=sutAb1zM9HBylcUOfxnQzVX00PtNaWVv /home/rafa/.virtualenvs/kaio/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/authorization_code.py 301
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  authorization-code

**Comment by JonathanHuot** [comment]
It should be `code` and not `authorization-code`. The former is the RFC value and the latter is an internal key value which should not be used from the client. Could you confirm that you're using this `response_type` from your client code ?

**Comment by Maronato** [comment]
Did you manage to get it to work, @rafahsolis?

**Comment by poswald** [comment]
Closing under the assumption that was the problem. Please reopen this if there is more to debug.

**Comment by bramski** [comment]
I'm having this exact problem trying to build a code authorization JSON endpoint for a mobile oauth provider. 
Provider application has:
"authorization_grant_type": "code"
and the client is requesting
`response_type: 'code'` and I'm getting `unauthorized_client`
