### ISSUE TITLE
axes.exceptions.AxesBackendRequestParameterRequired

### ISSUE THREAD

**Issue by developer-keev** [jazzband/django-oauth-toolkit#776]
I am developing a dockerized project in that need to implement account locked if retries exceeded with Axes package also using rest_framework_social_oauth2
**settings.py**
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    # social Authentication apps
    'oauth2_provider',
    'social_django',
    'rest_framework_social_oauth2',
    'axes'
    #...some other apps
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # OAuth
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]
AUTHENTICATION_BACKENDS = (
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesBackend',

    # Others auth providers (e.g. Google, OpenId, etc)
    # Google OAuth2
    'social_core.backends.google.GoogleOAuth2',

    # django-rest-framework-social-oauth2
    'rest_framework_social_oauth2.backends.DjangoOAuth2',

    # Django
    'django.contrib.auth.backends.ModelBackend',

)
```
Done migrations and added the new Application in your Django admin
And trying to get token

> curl -X POST -d "grant_type=convert_token&client_id=<django-oauth-generated-client_id>&client_secret=<django-oauth-generated-client_secret>&backend=google-oauth2&username=<username>&password=<password>" http://localhost:8000/social/token

But getting error as follows:

```
Traceback (most recent call last):
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1            |     response = get_response(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1            |     response = self.process_exception_by_middleware(e, request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1            |   File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
web_1            |     return func(*args, **kwds)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1            |     return view_func(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
web_1            |     return self.dispatch(request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
web_1            |     return bound_method(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1            |     return view_func(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/braces/views/_forms.py", line 30, in dispatch
web_1            |     return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
web_1            |     response = self.handle_exception(exc)
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
web_1            |     self.raise_uncaught_exception(exc)
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
web_1            |     raise exc
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
web_1            |     response = handler(request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework_social_oauth2/views.py", line 42, in post
web_1            |     url, headers, body, status = self.create_token_response(request._request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauth2_provider/views/mixins.py", line 123, in create_token_response
web_1            |     return core.create_token_response(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauth2_provider/oauth2_backends.py", line 138, in create_token_response
web_1            |     headers, extra_credentials)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 116, in wrapper
web_1            |     return f(endpoint, uri, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 119, in create_token_response
web_1            |     request, self.default_token_type)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 101, in create_token_response
web_1            |     self.validate_token_request(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 184, in validate_token_request
web_1            |     request.password, request.client, request):
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauth2_provider/oauth2_validators.py", line 594, in validate_user
web_1            |     u = authenticate(username=username, password=password)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
web_1            |     user = backend.authenticate(request, **credentials)
web_1            |   File "/usr/local/lib/python3.7/site-packages/axes/helpers.py", line 409, in inner
web_1            |     return func(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/axes/backends.py", line 39, in authenticate
web_1            |     "AxesBackend requires a request as an argument to authenticate"
web_1            | axes.exceptions.AxesBackendRequestParameterRequired: AxesBackend requires a request as an argument to authenticate
web_1            | [14/Jan/2020 16:58:57] "POST /api/social/token HTTP/1.1" 500 19614
```

I know how to solve this problem but I think it should be in the main package, so that can be installed by pip.

**Solution:**

**oauth_validators.py** line 590

```
def validate_user(self, username, password, client, request, *args, **kwargs):
        u = authenticate(username=username, password=password, request=request)
        if u is not None and u.is_active:
            request.user = u
            return True
        return False
```

Help me for this, Thanks

**Comment by Abhishek8394** [comment]
Are you referring to `https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L607-L611`[https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L607-L611] by any chance? The master already passes the request parameter.

**Comment by developer-keev** [comment]
Yes, I'm referring to this. But when am installing this package by pip, the installed package "oauth2_provider" version (1.2.0)  getting this code shown in the screenshot.

![Screenshot from 2020-01-16 11-51-37](https://user-images.githubusercontent.com/56814613/72499083-e5aec300-3856-11ea-8db5-cd32583a5dbc.png)

**Comment by developer-keev** [comment]
> Are you referring to https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L607-L611 by any chance? The master already passes the request parameter.

Tried this code by cloning from https://github.com/jazzband/django-oauth-toolkit.git 
But it's having the error that request doesn't have _META attribute
Because of that request isn't a django request.
```

web_1            | Internal Server Error: /api/social/token
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1            |     response = get_response(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1            |     response = self.process_exception_by_middleware(e, request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1            |   File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
web_1            |     return func(*args, **kwds)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1            |     return view_func(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
web_1            |     return self.dispatch(request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
web_1            |     return bound_method(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1            |     return view_func(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/braces/views/_forms.py", line 30, in dispatch
web_1            |     return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
web_1            |     response = self.handle_exception(exc)
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
web_1            |     self.raise_uncaught_exception(exc)
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
web_1            |     raise exc
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
web_1            |     response = handler(request, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/rest_framework_social_oauth2/views.py", line 42, in post
web_1            |     url, headers, body, status = self.create_token_response(request._request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauth2_provider/views/mixins.py", line 124, in create_token_response
web_1            |     return core.create_token_response(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauth2_provider/oauth2_backends.py", line 145, in create_token_response
web_1            |     headers, extra_credentials)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 116, in wrapper
web_1            |     return f(endpoint, uri, *args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 119, in create_token_response
web_1            |     request, self.default_token_type)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 101, in create_token_response
web_1            |     self.validate_token_request(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 184, in validate_token_request
web_1            |     request.password, request.client, request):
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauth2_provider/oauth2_validators.py", line 611, in validate_user
web_1            |     u = authenticate(request, username=username, password=password)
web_1            |   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
web_1            |     user = backend.authenticate(request, **credentials)
web_1            |   File "/usr/local/lib/python3.7/site-packages/axes/helpers.py", line 409, in inner
web_1            |     return func(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.7/site-packages/axes/backends.py", line 44, in authenticate
web_1            |     if AxesProxyHandler.is_allowed(request, credentials):
web_1            |   File "/usr/local/lib/python3.7/site-packages/axes/handlers/proxy.py", line 81, in is_allowed
web_1            |     cls.update_request(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/axes/handlers/proxy.py", line 69, in update_request
web_1            |     request.axes_ip_address = get_client_ip_address(request)
web_1            |   File "/usr/local/lib/python3.7/site-packages/axes/helpers.py", line 162, in get_client_ip_address
web_1            |     request_header_order=settings.AXES_META_PRECEDENCE_ORDER,
web_1            |   File "/usr/local/lib/python3.7/site-packages/ipware/ip2.py", line 25, in get_client_ip
web_1            |     value = util.get_request_meta(request, key)
web_1            |   File "/usr/local/lib/python3.7/site-packages/ipware/utils.py", line 66, in get_request_meta
web_1            |     value = request.META.get(key, request.META.get(key.replace('_', '-'), '')).strip()
web_1            |   File "/usr/local/lib/python3.7/site-packages/oauthlib/common.py", line 436, in __getattr__
web_1            |     raise AttributeError(name)
web_1            | AttributeError: META
```
So that found one solution from Axes Documentation 
> https://django-axes.readthedocs.io/en/latest/6_integration.html#integration-with-django-oauth-toolkit

This issue is solved.

**Comment by MattBlack85** [comment]
Solved
