### ISSUE TITLE
Subclassing grant model

### ISSUE THREAD

**Issue by indigodomo** [jazzband/django-oauth-toolkit#781]
I have the need to add a field to the grant model. I've subclassed thusly:

    class GrantWithLicense(AbstractGrant):
        transaction_id = models.IntegerField("Transaction ID", blank=True, null=True)

in a different app (account) models.py. When I attempt to **makemigration**, I get:

	Tracking file by folder pattern:  migrations
	Traceback (most recent call last):
	  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/django_manage.py", line 52, in <module>
		run_command()
	  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/django_manage.py", line 46, in run_command
		run_module(manage_file, None, '__main__', True)
	  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 205, in run_module
		return _run_module_code(code, init_globals, run_name, mod_spec)
	  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
		mod_name, mod_spec, pkg_name, script_name)
	  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
		exec(code, run_globals)
	  File "/Users/USER/Projects/Python/PROJECTPATH/manage.py", line 10, in <module>
		execute_from_command_line(sys.argv)
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
		utility.execute()
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
		self.fetch_command(subcommand).run_from_argv(self.argv)
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
		self.execute(*args, **cmd_options)
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
		output = self.handle(*args, **options)
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
		res = handle_func(*args, **kwargs)
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 168, in handle
		migration_name=self.migration_name,
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 43, in changes
		changes = self._detect_changes(convert_apps, graph)
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 194, in _detect_changes
		self._sort_migrations()
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 349, in _sort_migrations
		dep = self._resolve_dependency(dep)[0]
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 247, in _resolve_dependency
		resolved_app_label, resolved_object_name = getattr(settings, dependency[1]).split('.')
	  File "/Users/USER/Projects/Python/PROJECTPATH/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 80, in __getattr__
		val = getattr(self._wrapped, name)
	AttributeError: 'Settings' object has no attribute 'OAUTH2_PROVIDER_APPLICATION_MODEL'

I'm also upgrading my Django install to 2.2.1 (from 1.9) so there may be something about subclassing models in 2.2 that I'm not understanding.

**Comment by indigodomo** [comment]
Answer: the swappable models can't be specified in the main settings in the OAUTH2_PROVIDER namespace, but must be specified outside of it. So:

    OAUTH2_PROVIDER = {
        'ROTATE_REFRESH_TOKEN'       : True,
    }
    OAUTH2_PROVIDER_GRANT_MODEL = 'account.GrantWithLicense'
    OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'

rather than having the last two inside the OAUTH2_PROVIDER dict.
