### ISSUE TITLE
I am facing this error while using django-oauth-toolkit

### ISSUE THREAD

**Issue by abdulh01** [jazzband/django-oauth-toolkit#983]
Hi, I am trying to use Oauth authentication for my REST API built using DRF. I have created a custom user models called Account. I have followed all steps according to the Documentation. but when running command **py manage.py migrate** I am getting this error. I am new to this please help.

```
(env) E:\Django\cemd-api\app>python manage.py migrate oauth2_provider
Operations to perform:
  Apply all migrations: oauth2_provider
Running migrations:
  Applying oauth2_provider.0001_initial...Traceback (most recent call last):
  File "E:\Django\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "account_account" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Django\cemd-api\app\manage.py", line 22, in <module>
    main()
  File "E:\Django\cemd-api\app\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "E:\Django\env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "E:\Django\env\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "E:\Django\env\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "E:\Django\env\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "E:\Django\env\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "E:\Django\env\lib\site-packages\django\core\management\commands\migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "E:\Django\env\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "E:\Django\env\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "E:\Django\env\lib\site-packages\django\db\migrations\executor.py", line 230, in apply_migration
    migration_recorded = True
  File "E:\Django\env\lib\site-packages\django\db\backends\base\schema.py", line 118, in __exit__
    self.execute(sql)
  File "E:\Django\env\lib\site-packages\django\db\backends\base\schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "E:\Django\env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "E:\Django\env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\Django\env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\Django\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Django\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Django\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "account_account" does not exist
```

My Code in settings
```
INSTALLED_APPS=[
'oauth2_provider'
]
REST_FRAMEWORK={

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
}

AUTH_USER_MODEL = "account.Account"
```

**Note: ** Before doing this I have deleted all migrations and their tables in database.

**Comment by abdulh01** [comment]
Please help!!!!

**Comment by jnm** [comment]
> I have created a custom user models called Account.
> …
> **Note: ** Before doing this I have deleted all migrations and their tables in database.

You need to add the migration that creates your custom user model, otherwise almost every other Django migration is likely to fail. That's what the error is trying to tell you: `django.db.utils.ProgrammingError: relation "account_account" does not exist`. The `account_account` relation is the table for your `account.Account` model, and it needs to exist before the django-oauth-toolkit migrations can succeed.
