### ISSUE TITLE
ModuleNotFoundError: No module named 'oauth2_provider'

### ISSUE THREAD

**Issue by fred2012** [jazzband/django-oauth-toolkit#996]
after Add ` oauth2_provider ` to `INSTALLED_APPS`  in iam/settings.py
then execute the `python manage.py migrate`, showing the output in below:

`python manage.py migrate                                ░▒▓ ✔ │ iam   │ 21:25:33 
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/fangrzhang/Library/Python/3.7/lib/python/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/fangrzhang/Library/Python/3.7/lib/python/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/fangrzhang/Library/Python/3.7/lib/python/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/fangrzhang/Library/Python/3.7/lib/python/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/fangrzhang/Library/Python/3.7/lib/python/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'oauth2_provider'`

system environment:
`pip list                                                ░▒▓ 1 ✘ │ iam   │ 21:25:42 
Package              Version
-------------------- ---------
asgiref              3.4.1
certifi              2021.5.30
charset-normalizer   2.0.3
Django               3.2.5
django-oauth-toolkit 1.3.3
idna                 3.2
oauthlib             3.1.1
pip                  21.1.3
pytz                 2021.1
requests             2.26.0
setuptools           57.1.0
sqlparse             0.4.1
typing-extensions    3.10.0.0
urllib3              1.26.6
wheel                0.36.2`
`python --version                                        ░▒▓ ✔ │ iam   │ 21:35:05 
Python 3.7.6`

**Comment by dopry** [comment]
Try the latest release of DOT. If this is still an issue please re-open.
